# bproto/config.py

PROTOCOL_ID = b'BPROTO_V2'
DISCOVERY_PORT = 7001
TCP_PORT = 7002

CHUNK_SIZE = 1024 * 1024 * 4
SESSION_TIMEOUT = 3600
CONNECTION_TIMEOUT = 10

DEFAULT_SECRET = "ernoba-root"
DEFAULT_SAVE_DIR = "BProto_Received"

# WAJIB FALSE AGAR TIDAK ERROR "LIBRARY NOT FOUND"
ENABLE_ENCRYPTION = False   
ENABLE_COMPRESSION = False
VERIFY_INTEGRITY = True